title: Sanjana Prasad
logo: /assets/IMG_9838.JPG
description: I am a Data Science graduate student at Boston University. I completed my Bachelor’s degree in Electronics and Communication Engineering at PES University.  

This summer, I interned at Dassault Systemes as a Data Science Intern, where I worked on improving data pipelines for **[BIOVIA's Pipeline Pilot](https://www.3ds.com/products/biovia/pipeline-pilot)**.

#show_downloads: true
theme: jekyll-theme-minimal
#theme: jekyll-theme-just-the-docs

